module.exports = {
  en: { home: 'Home', research: 'Research', language: 'Language', quick: 'Quick answer', updated: 'Updated', published: 'first published', byline: 'By the LLM CFO team', related: 'Related', back: 'Back to llmcfo.com', privacy: 'Privacy', terms: 'Terms', security: 'Security', auditLead: 'Auditing your own LLM spend?', auditBody: 'LLM CFO runs a free audit of your AI costs and shows which workloads are driving the bill.', auditButton: 'Book a free audit', bottomLead: 'Want this applied to your stack?', bottomBody: 'Bring the provider bills, gateway logs, and top workflows; we will map the cost drivers and savings path.' },
  es: { home: 'Inicio', research: 'Investigación', language: 'Idioma', quick: 'Respuesta rápida', updated: 'Actualizado', published: 'publicado originalmente', byline: 'Por el equipo de LLM CFO', related: 'Relacionado', back: 'Volver a llmcfo.com', privacy: 'Privacidad', terms: 'Términos', security: 'Seguridad', auditLead: '¿Quieres auditar tu gasto en LLM?', auditBody: 'LLM CFO ofrece una auditoría gratuita de tus costes de IA e identifica las cargas que impulsan la factura.', auditButton: 'Solicitar auditoría gratuita', bottomLead: '¿Quieres aplicar esto a tu plataforma?', bottomBody: 'Comparte las facturas, los registros de la pasarela y los flujos principales; identificaremos los costes y las oportunidades de ahorro.' },
  fr: { home: 'Accueil', research: 'Recherche', language: 'Langue', quick: 'Réponse rapide', updated: 'Mis à jour', published: 'première publication', byline: 'Par l’équipe LLM CFO', related: 'À lire aussi', back: 'Retour à llmcfo.com', privacy: 'Confidentialité', terms: 'Conditions', security: 'Sécurité', auditLead: 'Vous souhaitez auditer vos dépenses LLM ?', auditBody: 'LLM CFO réalise un audit gratuit de vos coûts d’IA et identifie les charges qui pèsent sur la facture.', auditButton: 'Demander un audit gratuit', bottomLead: 'Vous souhaitez appliquer cela à votre plateforme ?', bottomBody: 'Transmettez vos factures fournisseurs, journaux de passerelle et principaux workflows ; nous cartographierons les coûts et les économies possibles.' },
  de: { home: 'Startseite', research: 'Forschung', language: 'Sprache', quick: 'Kurzantwort', updated: 'Aktualisiert', published: 'erstveröffentlicht', byline: 'Vom LLM-CFO-Team', related: 'Weiterführend', back: 'Zurück zu llmcfo.com', privacy: 'Datenschutz', terms: 'Bedingungen', security: 'Sicherheit', auditLead: 'Möchten Sie Ihre LLM-Ausgaben prüfen?', auditBody: 'LLM CFO prüft Ihre KI-Kosten kostenlos und zeigt, welche Workloads die Rechnung treiben.', auditButton: 'Kostenlose Prüfung buchen', bottomLead: 'Möchten Sie das auf Ihren Stack anwenden?', bottomBody: 'Bringen Sie Anbieterrechnungen, Gateway-Protokolle und die wichtigsten Workflows mit; wir ordnen Kostentreiber und Einsparpotenziale zu.' },
  ja: { home: 'ホーム', research: '調査', language: '言語', quick: '要約', updated: '更新日', published: '初回公開', byline: 'LLM CFO チーム', related: '関連記事', back: 'llmcfo.com に戻る', privacy: 'プライバシー', terms: '利用規約', security: 'セキュリティ', auditLead: 'LLM 支出を監査しませんか？', auditBody: 'LLM CFO は AI コストを無料で監査し、請求額を押し上げるワークロードを特定します。', auditButton: '無料監査を予約', bottomLead: 'この方法を自社の環境にも適用しますか？', bottomBody: 'プロバイダーの請求書、ゲートウェイログ、主要なワークフローをお持ちください。コスト要因と削減策を整理します。' },
  pt: { home: 'Início', research: 'Investigação', language: 'Idioma', quick: 'Resposta rápida', updated: 'Atualizado', published: 'publicado originalmente', byline: 'Pela equipa LLM CFO', related: 'Artigos relacionados', back: 'Voltar a llmcfo.com', privacy: 'Privacidade', terms: 'Termos', security: 'Segurança', auditLead: 'Quer auditar os custos dos seus LLM?', auditBody: 'A LLM CFO faz uma auditoria gratuita aos custos de IA e identifica as cargas de trabalho que aumentam a fatura.', auditButton: 'Marcar auditoria gratuita', bottomLead: 'Quer aplicar isto à sua plataforma?', bottomBody: 'Traga as faturas dos fornecedores, os registos do gateway e os principais fluxos de trabalho; mapearemos os custos e as oportunidades de poupança.' },
  it: { home: 'Home', research: 'Ricerca', language: 'Lingua', quick: 'Risposta rapida', updated: 'Aggiornato', published: 'pubblicato inizialmente', byline: 'Dal team LLM CFO', related: 'Correlati', back: 'Torna a llmcfo.com', privacy: 'Privacy', terms: 'Termini', security: 'Sicurezza', auditLead: 'Vuoi verificare la spesa per gli LLM?', auditBody: 'LLM CFO offre un audit gratuito dei costi IA e individua i carichi di lavoro che determinano la fattura.', auditButton: 'Prenota un audit gratuito', bottomLead: 'Vuoi applicarlo al tuo stack?', bottomBody: 'Porta le fatture dei provider, i log del gateway e i flussi di lavoro principali: mapperemo i costi e i possibili risparmi.' },
  ko: { home: '홈', research: '연구', language: '언어', quick: '핵심 답변', updated: '업데이트', published: '최초 게시', byline: 'LLM CFO 팀', related: '관련 글', back: 'llmcfo.com으로 돌아가기', privacy: '개인정보 보호', terms: '약관', security: '보안', auditLead: 'LLM 지출을 점검하고 싶으신가요?', auditBody: 'LLM CFO는 AI 비용을 무료로 점검하고 청구액을 높이는 워크로드를 찾아드립니다.', auditButton: '무료 감사 예약', bottomLead: '이 내용을 현재 스택에 적용하고 싶으신가요?', bottomBody: '공급업체 청구서, 게이트웨이 로그, 주요 워크플로를 가져오시면 비용 요인과 절감 경로를 정리해드립니다.' },
  zh: { home: '首页', research: '研究', language: '语言', quick: '快速结论', updated: '更新于', published: '首次发布', byline: 'LLM CFO 团队', related: '相关文章', back: '返回 llmcfo.com', privacy: '隐私', terms: '条款', security: '安全', auditLead: '想审查您的 LLM 支出吗？', auditBody: 'LLM CFO 免费审查 AI 成本，并找出推高账单的工作负载。', auditButton: '预约免费审查', bottomLead: '想将这些方法用于您的技术栈吗？', bottomBody: '请准备好供应商账单、网关日志和主要工作流；我们会梳理成本驱动因素与节省空间。' },
  nl: { home: 'Home', research: 'Onderzoek', language: 'Taal', quick: 'Kort antwoord', updated: 'Bijgewerkt', published: 'eerst gepubliceerd', byline: 'Door het LLM CFO-team', related: 'Gerelateerd', back: 'Terug naar llmcfo.com', privacy: 'Privacy', terms: 'Voorwaarden', security: 'Beveiliging', auditLead: 'Wilt u uw LLM-uitgaven laten controleren?', auditBody: 'LLM CFO voert gratis een controle uit van uw AI-kosten en laat zien welke workloads de rekening verhogen.', auditButton: 'Plan een gratis audit', bottomLead: 'Wilt u dit toepassen op uw stack?', bottomBody: 'Neem leveranciersfacturen, gatewaylogs en de belangrijkste workflows mee; we brengen kostenfactoren en besparingskansen in kaart.' },
  ar: { home: 'الرئيسية', research: 'الأبحاث', language: 'اللغة', quick: 'إجابة سريعة', updated: 'آخر تحديث', published: 'نُشر أول مرة', byline: 'فريق LLM CFO', related: 'مقالات ذات صلة', back: 'العودة إلى llmcfo.com', privacy: 'الخصوصية', terms: 'الشروط', security: 'الأمان', auditLead: 'هل تريد تدقيق إنفاقك على نماذج اللغة؟', auditBody: 'تجري LLM CFO تدقيقًا مجانيًا لتكاليف الذكاء الاصطناعي وتحدد أعباء العمل التي ترفع الفاتورة.', auditButton: 'احجز تدقيقًا مجانيًا', bottomLead: 'هل تريد تطبيق ذلك على منصتك؟', bottomBody: 'أحضر فواتير المزوّدين وسجلات البوابة وأهم تدفقات العمل؛ وسنحدد محركات التكلفة وفرص التوفير.' }
};

const articleNavigationLabels = {
  en: { benchmarks: 'Benchmarks', about: 'About', article: 'Article breadcrumb', navigation: 'Main navigation', skip: 'Skip to content' },
  es: { benchmarks: 'Referencias', about: 'Acerca de', article: 'Ruta del artículo', navigation: 'Navegación principal', skip: 'Saltar al contenido' },
  fr: { benchmarks: 'Références', about: 'À propos', article: 'Fil de l’article', navigation: 'Navigation principale', skip: 'Aller au contenu' },
  de: { benchmarks: 'Benchmarks', about: 'Über uns', article: 'Artikelpfad', navigation: 'Hauptnavigation', skip: 'Zum Inhalt' },
  ja: { benchmarks: 'ベンチマーク', about: '概要', article: '記事のパンくずリスト', navigation: 'メインナビゲーション', skip: '本文へ移動' },
  pt: { benchmarks: 'Referências', about: 'Sobre', article: 'Navegação estrutural do artigo', navigation: 'Navegação principal', skip: 'Saltar para o conteúdo' },
  it: { benchmarks: 'Benchmark', about: 'Chi siamo', article: 'Percorso dell’articolo', navigation: 'Navigazione principale', skip: 'Vai al contenuto' },
  ko: { benchmarks: '벤치마크', about: '소개', article: '문서 경로', navigation: '주요 탐색', skip: '본문으로 건너뛰기' },
  zh: { benchmarks: '基准', about: '关于', article: '文章导航路径', navigation: '主导航', skip: '跳转到正文' },
  nl: { benchmarks: 'Benchmarks', about: 'Over ons', article: 'Artikelpad', navigation: 'Hoofdnavigatie', skip: 'Ga naar inhoud' },
  ar: { benchmarks: 'المعايير', about: 'من نحن', article: 'مسار المقالة', navigation: 'التنقل الرئيسي', skip: 'انتقل إلى المحتوى' }
};
for (const [lang, labels] of Object.entries(articleNavigationLabels)) {
  Object.assign(module.exports[lang], labels);
}

// Keep English as the fallback for any label added before its translations land.
const englishDefaults = module.exports.en;
for (const [lang, labels] of Object.entries(module.exports)) {
  module.exports[lang] = Object.assign({}, englishDefaults, labels);
}
